package model.ERP.EO;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.adf.share.ADFContext;

import oracle.jbo.Key;
import oracle.jbo.domain.Number;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Sep 08 16:39:57 PKT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TblEditFeeCollDImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Id,
        EditFeeCollMId,
        FeeTypeId,
        Amount,
        CreatedDate,
        CreatedBy,
        UpdatedDate,
        UpdatedBy,
        TblEditFeeCollM;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int ID = AttributesEnum.Id.index();
    public static final int EDITFEECOLLMID = AttributesEnum.EditFeeCollMId.index();
    public static final int FEETYPEID = AttributesEnum.FeeTypeId.index();
    public static final int AMOUNT = AttributesEnum.Amount.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int UPDATEDDATE = AttributesEnum.UpdatedDate.index();
    public static final int UPDATEDBY = AttributesEnum.UpdatedBy.index();
    public static final int TBLEDITFEECOLLM = AttributesEnum.TblEditFeeCollM.index();

    /**
     * This is the default constructor (do not remove).
     */
    public TblEditFeeCollDImpl() {
    }

    /**
     * Gets the attribute value for Id, using the alias name Id.
     * @return the value of Id
     */
    public BigDecimal getId() {
        return (BigDecimal) getAttributeInternal(ID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Id.
     * @param value value to set the Id
     */
    public void setId(BigDecimal value) {
        setAttributeInternal(ID, value);
    }

    /**
     * Gets the attribute value for EditFeeCollMId, using the alias name EditFeeCollMId.
     * @return the value of EditFeeCollMId
     */
    public BigDecimal getEditFeeCollMId() {
        return (BigDecimal) getAttributeInternal(EDITFEECOLLMID);
    }

    /**
     * Sets <code>value</code> as the attribute value for EditFeeCollMId.
     * @param value value to set the EditFeeCollMId
     */
    public void setEditFeeCollMId(BigDecimal value) {
        setAttributeInternal(EDITFEECOLLMID, value);
    }

    /**
     * Gets the attribute value for FeeTypeId, using the alias name FeeTypeId.
     * @return the value of FeeTypeId
     */
    public BigDecimal getFeeTypeId() {
        return (BigDecimal) getAttributeInternal(FEETYPEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for FeeTypeId.
     * @param value value to set the FeeTypeId
     */
    public void setFeeTypeId(BigDecimal value) {
        setAttributeInternal(FEETYPEID, value);
    }

    /**
     * Gets the attribute value for Amount, using the alias name Amount.
     * @return the value of Amount
     */
    public BigDecimal getAmount() {
        return (BigDecimal) getAttributeInternal(AMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for Amount.
     * @param value value to set the Amount
     */
    public void setAmount(BigDecimal value) {
        setAttributeInternal(AMOUNT, value);
    }

    /**
     * Gets the attribute value for CreatedDate, using the alias name CreatedDate.
     * @return the value of CreatedDate
     */
    public Timestamp getCreatedDate() {
        return (Timestamp) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the value of CreatedBy
     */
    public Number getCreatedBy() {
        return (Number) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for UpdatedDate, using the alias name UpdatedDate.
     * @return the value of UpdatedDate
     */
    public Timestamp getUpdatedDate() {
        return (Timestamp) getAttributeInternal(UPDATEDDATE);
    }

    /**
     * Gets the attribute value for UpdatedBy, using the alias name UpdatedBy.
     * @return the value of UpdatedBy
     */
    public Number getUpdatedBy() {
        return (Number) getAttributeInternal(UPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for UpdatedBy.
     * @param value value to set the UpdatedBy
     */
    public void setUpdatedBy(Number value) {
        setAttributeInternal(UPDATEDBY, value);
    }

    /**
     * @return the associated entity TblEditFeeCollMImpl.
     */
    public TblEditFeeCollMImpl getTblEditFeeCollM() {
        return (TblEditFeeCollMImpl) getAttributeInternal(TBLEDITFEECOLLM);
    }

    /**
     * Sets <code>value</code> as the associated entity TblEditFeeCollMImpl.
     */
    public void setTblEditFeeCollM(TblEditFeeCollMImpl value) {
        setAttributeInternal(TBLEDITFEECOLLM, value);
    }

    /**
     * @param id key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(BigDecimal id) {
        return new Key(new Object[] { id });
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("model.ERP.EO.TblEditFeeCollD");
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        Number loginId = null;
                       try {
                           loginId = new Number((String) ADFContext.getCurrent().getSessionScope().get("sessUMID"));
                       } catch(Exception ex) {
                           ex.printStackTrace();
                       }
                       
                       if (operation == DML_INSERT) {
                           setCreatedBy(loginId);
                           setUpdatedBy(loginId);
                           } else if(operation == DML_UPDATE) {
                           setUpdatedBy(loginId);
                       }
        super.doDML(operation, e);
    }
}

