package model.ERP.EO;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.adf.share.ADFContext;

import oracle.jbo.Key;
import oracle.jbo.domain.Number;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Jun 26 11:28:59 PKT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TblOpenBlncImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        OpenBlncId,
        OpenBlncDated,
        OpenBlncGlL4Id,
        OpenBlncDr,
        OpenBlncCr,
        GroupCompanyId,
        CompanySbuId,
        CreatedBy,
        CreatedDate,
        UpdatedBy,
        UpdatedDate,
        TblGlL4;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int OPENBLNCID = AttributesEnum.OpenBlncId.index();
    public static final int OPENBLNCDATED = AttributesEnum.OpenBlncDated.index();
    public static final int OPENBLNCGLL4ID = AttributesEnum.OpenBlncGlL4Id.index();
    public static final int OPENBLNCDR = AttributesEnum.OpenBlncDr.index();
    public static final int OPENBLNCCR = AttributesEnum.OpenBlncCr.index();
    public static final int GROUPCOMPANYID = AttributesEnum.GroupCompanyId.index();
    public static final int COMPANYSBUID = AttributesEnum.CompanySbuId.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int UPDATEDBY = AttributesEnum.UpdatedBy.index();
    public static final int UPDATEDDATE = AttributesEnum.UpdatedDate.index();
    public static final int TBLGLL4 = AttributesEnum.TblGlL4.index();

    /**
     * This is the default constructor (do not remove).
     */
    public TblOpenBlncImpl() {
    }

    /**
     * Gets the attribute value for OpenBlncId, using the alias name OpenBlncId.
     * @return the value of OpenBlncId
     */
    public BigDecimal getOpenBlncId() {
        return (BigDecimal) getAttributeInternal(OPENBLNCID);
    }

    /**
     * Sets <code>value</code> as the attribute value for OpenBlncId.
     * @param value value to set the OpenBlncId
     */
    public void setOpenBlncId(BigDecimal value) {
        setAttributeInternal(OPENBLNCID, value);
    }

    /**
     * Gets the attribute value for OpenBlncDated, using the alias name OpenBlncDated.
     * @return the value of OpenBlncDated
     */
    public Timestamp getOpenBlncDated() {
        return (Timestamp) getAttributeInternal(OPENBLNCDATED);
    }

    /**
     * Sets <code>value</code> as the attribute value for OpenBlncDated.
     * @param value value to set the OpenBlncDated
     */
    public void setOpenBlncDated(Timestamp value) {
        setAttributeInternal(OPENBLNCDATED, value);
    }

    /**
     * Gets the attribute value for OpenBlncGlL4Id, using the alias name OpenBlncGlL4Id.
     * @return the value of OpenBlncGlL4Id
     */
    public BigDecimal getOpenBlncGlL4Id() {
        return (BigDecimal) getAttributeInternal(OPENBLNCGLL4ID);
    }

    /**
     * Sets <code>value</code> as the attribute value for OpenBlncGlL4Id.
     * @param value value to set the OpenBlncGlL4Id
     */
    public void setOpenBlncGlL4Id(BigDecimal value) {
        setAttributeInternal(OPENBLNCGLL4ID, value);
    }

    /**
     * Gets the attribute value for OpenBlncDr, using the alias name OpenBlncDr.
     * @return the value of OpenBlncDr
     */
    public BigDecimal getOpenBlncDr() {
        return (BigDecimal) getAttributeInternal(OPENBLNCDR);
    }

    /**
     * Sets <code>value</code> as the attribute value for OpenBlncDr.
     * @param value value to set the OpenBlncDr
     */
    public void setOpenBlncDr(BigDecimal value) {
        setAttributeInternal(OPENBLNCDR, value);
    }

    /**
     * Gets the attribute value for OpenBlncCr, using the alias name OpenBlncCr.
     * @return the value of OpenBlncCr
     */
    public BigDecimal getOpenBlncCr() {
        return (BigDecimal) getAttributeInternal(OPENBLNCCR);
    }

    /**
     * Sets <code>value</code> as the attribute value for OpenBlncCr.
     * @param value value to set the OpenBlncCr
     */
    public void setOpenBlncCr(BigDecimal value) {
        setAttributeInternal(OPENBLNCCR, value);
    }

    /**
     * Gets the attribute value for GroupCompanyId, using the alias name GroupCompanyId.
     * @return the value of GroupCompanyId
     */
    public Number getGroupCompanyId() {
        return (Number) getAttributeInternal(GROUPCOMPANYID);
    }

    /**
     * Sets <code>value</code> as the attribute value for GroupCompanyId.
     * @param value value to set the GroupCompanyId
     */
    public void setGroupCompanyId(Number value) {
        setAttributeInternal(GROUPCOMPANYID, value);
    }

    /**
     * Gets the attribute value for CompanySbuId, using the alias name CompanySbuId.
     * @return the value of CompanySbuId
     */
    public Number getCompanySbuId() {
        return (Number) getAttributeInternal(COMPANYSBUID);
    }

    /**
     * Sets <code>value</code> as the attribute value for CompanySbuId.
     * @param value value to set the CompanySbuId
     */
    public void setCompanySbuId(Number value) {
        setAttributeInternal(COMPANYSBUID, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the value of CreatedBy
     */
    public Number getCreatedBy() {
        return (Number) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreatedDate, using the alias name CreatedDate.
     * @return the value of CreatedDate
     */
    public Timestamp getCreatedDate() {
        return (Timestamp) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedDate.
     * @param value value to set the CreatedDate
     */
    public void setCreatedDate(Timestamp value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for UpdatedBy, using the alias name UpdatedBy.
     * @return the value of UpdatedBy
     */
    public Number getUpdatedBy() {
        return (Number) getAttributeInternal(UPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for UpdatedBy.
     * @param value value to set the UpdatedBy
     */
    public void setUpdatedBy(Number value) {
        setAttributeInternal(UPDATEDBY, value);
    }

    /**
     * Gets the attribute value for UpdatedDate, using the alias name UpdatedDate.
     * @return the value of UpdatedDate
     */
    public Timestamp getUpdatedDate() {
        return (Timestamp) getAttributeInternal(UPDATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for UpdatedDate.
     * @param value value to set the UpdatedDate
     */
    public void setUpdatedDate(Timestamp value) {
        setAttributeInternal(UPDATEDDATE, value);
    }

    /**
     * @return the associated entity TblGlL4Impl.
     */
    public TblGlL4Impl getTblGlL4() {
        return (TblGlL4Impl) getAttributeInternal(TBLGLL4);
    }

    /**
     * Sets <code>value</code> as the associated entity TblGlL4Impl.
     */
    public void setTblGlL4(TblGlL4Impl value) {
        setAttributeInternal(TBLGLL4, value);
    }

    /**
     * @param openBlncId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(BigDecimal openBlncId) {
        return new Key(new Object[] { openBlncId });
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("model.ERP.EO.TblOpenBlnc");
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        Number userId = null;
        Number cmpnyId = null;
        Number sbuId = null;
         try {
             userId = new Number((String) ADFContext.getCurrent().getSessionScope().get("sessUMID"));
             cmpnyId = new Number((String) ADFContext.getCurrent().getSessionScope().get("sessCmpnyID"));
             sbuId = new Number((String) ADFContext.getCurrent().getSessionScope().get("sessSBUID"));
         } catch(Exception ex) {
             ex.printStackTrace();
         }
         
         if (operation == DML_INSERT) {

             setGroupCompanyId(cmpnyId);
             setCompanySbuId(sbuId);

             setCreatedBy(userId);
             setUpdatedBy(userId);
             } else if(operation == DML_UPDATE) {
             
             setGroupCompanyId(cmpnyId);
             setCompanySbuId(sbuId);
             
             setUpdatedBy(userId);
         }
        super.doDML(operation, e);
    }
}

