package model.ERP.EO;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.adf.share.ADFContext;

import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.Number;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Apr 01 14:26:12 PKT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TblTransportImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Id,
        TransportNo,
        RegNo,
        EngineNo,
        ChasisNo,
        LookupTransportType,
        StaffId,
        Ast,
        CreatedDate,
        CreatedBy,
        UpdatedDate,
        UpdatedBy,
        TblRoute;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int ID = AttributesEnum.Id.index();
    public static final int TRANSPORTNO = AttributesEnum.TransportNo.index();
    public static final int REGNO = AttributesEnum.RegNo.index();
    public static final int ENGINENO = AttributesEnum.EngineNo.index();
    public static final int CHASISNO = AttributesEnum.ChasisNo.index();
    public static final int LOOKUPTRANSPORTTYPE = AttributesEnum.LookupTransportType.index();
    public static final int STAFFID = AttributesEnum.StaffId.index();
    public static final int AST = AttributesEnum.Ast.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int UPDATEDDATE = AttributesEnum.UpdatedDate.index();
    public static final int UPDATEDBY = AttributesEnum.UpdatedBy.index();
    public static final int TBLROUTE = AttributesEnum.TblRoute.index();

    /**
     * This is the default constructor (do not remove).
     */
    public TblTransportImpl() {
    }

    /**
     * Gets the attribute value for Id, using the alias name Id.
     * @return the value of Id
     */
    public BigDecimal getId() {
        return (BigDecimal) getAttributeInternal(ID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Id.
     * @param value value to set the Id
     */
    public void setId(BigDecimal value) {
        setAttributeInternal(ID, value);
    }

    /**
     * Gets the attribute value for TransportNo, using the alias name TransportNo.
     * @return the value of TransportNo
     */
    public String getTransportNo() {
        return (String) getAttributeInternal(TRANSPORTNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for TransportNo.
     * @param value value to set the TransportNo
     */
    public void setTransportNo(String value) {
        setAttributeInternal(TRANSPORTNO, value);
    }

    /**
     * Gets the attribute value for RegNo, using the alias name RegNo.
     * @return the value of RegNo
     */
    public String getRegNo() {
        return (String) getAttributeInternal(REGNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for RegNo.
     * @param value value to set the RegNo
     */
    public void setRegNo(String value) {
        setAttributeInternal(REGNO, value);
    }

    /**
     * Gets the attribute value for EngineNo, using the alias name EngineNo.
     * @return the value of EngineNo
     */
    public String getEngineNo() {
        return (String) getAttributeInternal(ENGINENO);
    }

    /**
     * Sets <code>value</code> as the attribute value for EngineNo.
     * @param value value to set the EngineNo
     */
    public void setEngineNo(String value) {
        setAttributeInternal(ENGINENO, value);
    }

    /**
     * Gets the attribute value for ChasisNo, using the alias name ChasisNo.
     * @return the value of ChasisNo
     */
    public String getChasisNo() {
        return (String) getAttributeInternal(CHASISNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for ChasisNo.
     * @param value value to set the ChasisNo
     */
    public void setChasisNo(String value) {
        setAttributeInternal(CHASISNO, value);
    }

    /**
     * Gets the attribute value for LookupTransportType, using the alias name LookupTransportType.
     * @return the value of LookupTransportType
     */
    public BigDecimal getLookupTransportType() {
        return (BigDecimal) getAttributeInternal(LOOKUPTRANSPORTTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LookupTransportType.
     * @param value value to set the LookupTransportType
     */
    public void setLookupTransportType(BigDecimal value) {
        setAttributeInternal(LOOKUPTRANSPORTTYPE, value);
    }

    /**
     * Gets the attribute value for StaffId, using the alias name StaffId.
     * @return the value of StaffId
     */
    public BigDecimal getStaffId() {
        return (BigDecimal) getAttributeInternal(STAFFID);
    }

    /**
     * Sets <code>value</code> as the attribute value for StaffId.
     * @param value value to set the StaffId
     */
    public void setStaffId(BigDecimal value) {
        setAttributeInternal(STAFFID, value);
    }

    /**
     * Gets the attribute value for Ast, using the alias name Ast.
     * @return the value of Ast
     */
    public String getAst() {
        return (String) getAttributeInternal(AST);
    }

    /**
     * Sets <code>value</code> as the attribute value for Ast.
     * @param value value to set the Ast
     */
    public void setAst(String value) {
        setAttributeInternal(AST, value);
    }

    /**
     * Gets the attribute value for CreatedDate, using the alias name CreatedDate.
     * @return the value of CreatedDate
     */
    public Timestamp getCreatedDate() {
        return (Timestamp) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the value of CreatedBy
     */
    public Number getCreatedBy() {
        return (Number) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for UpdatedDate, using the alias name UpdatedDate.
     * @return the value of UpdatedDate
     */
    public Timestamp getUpdatedDate() {
        return (Timestamp) getAttributeInternal(UPDATEDDATE);
    }

    /**
     * Gets the attribute value for UpdatedBy, using the alias name UpdatedBy.
     * @return the value of UpdatedBy
     */
    public Number getUpdatedBy() {
        return (Number) getAttributeInternal(UPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for UpdatedBy.
     * @param value value to set the UpdatedBy
     */
    public void setUpdatedBy(Number value) {
        setAttributeInternal(UPDATEDBY, value);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getTblRoute() {
        return (RowIterator) getAttributeInternal(TBLROUTE);
    }

    /**
     * @param id key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(BigDecimal id) {
        return new Key(new Object[] { id });
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("model.ERP.EO.TblTransport");
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        Number loginId = null;
                 try {
                     loginId = new Number((String) ADFContext.getCurrent().getSessionScope().get("sessRID"));
                 } catch(Exception ex) {
                     ex.printStackTrace();
                 }
                 
                 if (operation == DML_INSERT) {
                     setCreatedBy(loginId);
                     setUpdatedBy(loginId);
                     } else if(operation == DML_UPDATE) {
                     setUpdatedBy(loginId);
                 }
        super.doDML(operation, e);
    }
}

